export const CATEGORIES = [
  { id: "1", name: "Электроника", icon: "MonitorSmartphone" },
  { id: "2", name: "Телефоны", icon: "Smartphone" },
  { id: "3", name: "Компьютеры", icon: "Laptop" },
  { id: "4", name: "Авто", icon: "Car" },
  { id: "5", name: "Недвижимость", icon: "Home" },
  { id: "6", name: "Одежда и обувь", icon: "Shirt" },
  { id: "7", name: "Дом и сад", icon: "Armchair" },
  { id: "8", name: "Детские товары", icon: "Baby" },
  { id: "9", name: "Красота и здоровье", icon: "HeartPulse" },
  { id: "10", name: "Спорт и отдых", icon: "Dumbbell" },
  { id: "11", name: "Животные", icon: "Cat" },
  { id: "12", name: "Работа", icon: "Briefcase" },
  { id: "13", name: "Услуги", icon: "Wrench" },
  { id: "14", name: "Бизнес", icon: "Building2" },
  { id: "15", name: "Ещё", icon: "MoreHorizontal" },
];

export const POPULAR_PRODUCTS = [
  {
    id: "p1",
    title: "iPhone 13 128 GB",
    price: 28000,
    city: "Бишкек",
    time: "2 часа назад",
    condition: "Отличное состояние",
    seller: { name: "Азамат", rating: 4.8, reviews: 124 },
    image: "/demo/products/iphone.jpg",
    isVerified: true,
    category: "Смартфоны"
  },
  {
    id: "p2",
    title: "MacBook Air M1",
    price: 48000,
    city: "Бишкек",
    time: "Вчера",
    condition: "Как новый",
    seller: { name: "TechStore", rating: 4.9, reviews: 342 },
    image: "/demo/products/macbook.jpg",
    isVerified: true,
    category: "Ноутбуки"
  },
  {
    id: "p3",
    title: "Nike Air Force 1",
    price: 6500,
    city: "Бишкек",
    time: "5 часов назад",
    condition: "Новые, оригинал",
    seller: { name: "SneakerShop", rating: 4.7, reviews: 89 },
    image: "/demo/products/nike.jpg",
    isVerified: false,
    category: "Одежда"
  },
  {
    id: "p4",
    title: "Toyota Camry 70",
    price: 2450000,
    city: "Бишкек",
    time: "3 дня назад",
    condition: "2018, 2.5, Бензин",
    seller: { name: "AutoKG", rating: 4.5, reviews: 56 },
    image: "/demo/products/camry.jpg",
    isVerified: true,
    category: "Авто"
  },
];

export const TRENDING_STORES = [
  {
    id: "s1",
    name: "TechStore",
    category: "Электроника",
    rating: 4.8,
    reviews: 324,
    avatar: "/demo/stores/techstore.jpg",
    isVerified: true,
  },
  {
    id: "s2",
    name: "AutoHouse",
    category: "Автомобили",
    rating: 4.7,
    reviews: 198,
    avatar: "/demo/stores/autohouse.jpg",
    isVerified: true,
  },
  {
    id: "s3",
    name: "HomeComfort",
    category: "Для дома",
    rating: 4.6,
    reviews: 176,
    avatar: "/demo/stores/homecomfort.jpg",
    isVerified: true,
  },
  {
    id: "s4",
    name: "StyleKG",
    category: "Одежда",
    rating: 4.9,
    reviews: 412,
    avatar: "/demo/stores/stylekg.jpg",
    isVerified: true,
  },
];
